### ISSUE TITLE
Start running aggregations by congressional districts

### ISSUE THREAD

**Issue by saikat** [Bernie-2016/EventCounter#1]
Right now, we are only doing aggregations by Craigslist regions.  To start aggregating by CD, @bahoo has a heroku set up with CongressionalDistrict shapefiles that we can use to get CD info from lat/long (I believe).

**Comment by saikat** [comment]
Talking to more people about it, this is not super high priority right now.  Congressional districts matter, but for the purposes of this dashboard, we are trying more to have people who self-identify with a particular place all be on calls together/see how their "region" is doing.  Congressional districts tend to be gerrymandered and, thus, matter politically but have less relevance to places people actually associate with.  The dashboard, right now, is a way for us to get people connected and wanting events, so for that purpose, it matters more that they see data about the regions they identify with (which Craigslist regions does a decent job of approximating).

**Comment by bahoo** [comment]
CD shapefiles, for some time in the future: http://cdmaps.polisci.ucla.edu/

In a similar thread / possibly useful, we'd talked about using this Leaflet heatmap plugin to visualize the density of supporters in your area: http://leaflet.github.io/Leaflet.heat/demo/

**Comment by saikat** [comment]
Also moving this to volunteer dashboard so we can track everything there.
